spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver #注册驱动
    url: jdbc:mysql://localhost:3306/cloudfactory
    username: root
    password: ShiQi2282

server:
  servlet:
    context-path: /cloudfactory   #设置项目名称
    jsp:
      init-parameters:
        development: true #开启jsp页面热部署
mybatis:
  mapper-locations: classpath:com/lyl/cloudfactory/mapper/*.xml #mapper配置文件的位置
  type-aliases-package: com.lyl.cloudfactory.entity
